Repository All-eatery/EatsFinder-FE, pull requests merged in 2024-07, with the labels that each got.

#24 Refactor/spacer
  src/app/(auth)/_components/AuthHeader.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/login/_components/LoginPage.tsx
  src/app/(auth)/login/_components/RecentLoginMsg.tsx
  src/app/(auth)/login/_components/SocialLoginBtn.tsx
Labels: ♻️ Refactor

#26 Feat/carousel
  next.config.mjs
  src/components/atoms/button/CarouselButton.stories.tsx
  src/components/atoms/button/CarouselButton.tsx
  src/components/atoms/button/index.ts
  src/components/molecules/card/FeedCard.stories.tsx
  src/components/molecules/card/FeedCard.tsx
  src/components/molecules/card/index.ts
  src/components/organisms/carousel/CardCarousel.stories.tsx
  src/components/organisms/carousel/CardCarousel.tsx
  src/components/organisms/carousel/index.ts
  src/components/organisms/index.ts
  src/components/svg/ArrowSVG.tsx
  src/components/svg/DownSVG.tsx
  src/components/svg/RightSVG.tsx
Labels: ✒️ Rename, ✨ Feat

#28 Feat/layout
  .storybook/preview.tsx
  src/app/(auth)/_components/AuthHeader.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/LoginPage.tsx
  src/app/layout.tsx
  src/components/atoms/index.ts
  src/components/atoms/navLink/NavLink.stories.tsx
  src/components/atoms/navLink/NavLink.tsx
  src/components/atoms/navLink/index.ts
  src/components/atoms/profileImage/ProfileImage.stories.tsx
  src/components/atoms/profileImage/ProfileImage.tsx
  src/components/atoms/profileImage/index.ts
  src/components/organisms/footer/Footer.stories.tsx
  src/components/organisms/footer/Footer.tsx
  src/components/organisms/footer/index.ts
  src/components/organisms/header/Header.stories.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/header/index.ts
  src/components/organisms/index.ts
Labels: ✨ Feat, 🐛 Fix, 💄 Style

#29 Feat/signup
  .env
  package-lock.json
  package.json
  src/app/(auth)/_components/VisibilityButtonIcon.tsx
  src/app/(auth)/_hooks/useAuth.ts
  src/app/(auth)/_hooks/useEmailConfirm.ts
  src/app/(auth)/_hooks/useFormData.ts
  src/app/(auth)/_hooks/useSaveLoginState.ts
  src/app/(auth)/_hooks/useTimer.ts
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/signup/_components/AgreeTerms.tsx
  src/app/(auth)/signup/_components/ConfirmEmail.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/_components/SignupPage.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_componets/Test.tsx
  src/app/api/auth/route.ts
  src/app/types/authType.ts
  src/components/atoms/textField/TextField.tsx
  src/components/molecules/texTFieldWithBtn/TexTFieldWithBtn.tsx
  src/hooks/useToggleHandler.ts
  src/types/authType.ts
  src/utils/zodSchema.ts
Labels: ✨ Feat

#30 Feat/home
  src/app/(auth)/login/_components/LoginPage.tsx
  src/app/_components/HomePage.tsx
  src/app/_componets/Test.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/images/asian.png
  src/assets/images/buffet.png
  src/assets/images/chinese.png
  src/assets/images/japanese.png
  src/assets/images/korean.png
  src/assets/images/others.png
  src/assets/images/snack.png
  src/assets/images/western.png
  src/components/atoms/hashtag/Hashtag.stories.tsx
  src/components/atoms/hashtag/Hashtag.tsx
  src/components/atoms/hashtag/index.ts
  src/components/atoms/image/CategoryImage.stories.tsx
  src/components/atoms/image/CategoryImage.tsx
  src/components/atoms/image/ProfileImage.stories.tsx
  src/components/atoms/image/ProfileImage.tsx
  src/components/atoms/image/index.ts
  src/components/atoms/index.ts
  src/components/atoms/profileImage/index.ts
  src/components/molecules/card/FeedCard.tsx
  src/components/molecules/card/FollowCard.stories.tsx
  src/components/molecules/card/FollowCard.tsx
  src/components/molecules/card/index.ts
  src/components/molecules/category/Category.stories.tsx
  src/components/molecules/category/Category.tsx
  src/components/molecules/category/index.ts
  src/components/molecules/homeSection/HomeSection.tsx
  src/components/molecules/homeSection/index.ts
  src/components/molecules/index.ts
  src/components/molecules/search/Search.stories.tsx
  src/components/molecules/search/Search.tsx
  src/components/molecules/search/index.ts
  src/components/svg/CloseSVG.tsx
  src/components/svg/HashtagSVG.tsx
  src/components/svg/UploadSVG.tsx
  src/constants/categoryImages.ts
Labels: ✨ Feat, 🍱 Add, 🧹 Remove

#33 Feat/signup
  .env
  .gitignore
  src/app/(auth)/_hooks/useEmailConfirm.ts
  src/app/(auth)/_hooks/useFormData.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/signup/_components/AgreeTerms.tsx
  src/app/(auth)/signup/_components/ConfirmEmail.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/globals.css
  src/components/atoms/checkbox/Checkbox.tsx
  src/components/atoms/textField/TextField.tsx
  src/components/molecules/texTFieldWithBtn/TexTFieldWithBtn.tsx
  src/types/authType.ts
  src/utils/zodSchema.ts
Labels: ✨ Feat, 🐛 Fix, 🧹 Remove

#39 Feat/modal
  src/components/molecules/index.ts
  src/components/molecules/modal/ModalFooter.stories.tsx
  src/components/molecules/modal/ModalFooter.tsx
  src/components/molecules/modal/ModalHeader.stories.tsx
  src/components/molecules/modal/ModalHeader.tsx
  src/components/molecules/modal/index.ts
  src/components/organisms/index.ts
  src/components/organisms/modal/Modal.stories.tsx
  src/components/organisms/modal/Modal.tsx
  src/components/organisms/modal/index.ts
Labels: ✨ Feat

#40 Feat/profile page
  src/app/(auth)/profile/[userId]/_components/FeedOptionMenu.tsx
  src/app/(auth)/profile/[userId]/_components/MyFeed.tsx
  src/app/(auth)/profile/[userId]/_components/Profile.tsx
  src/app/(auth)/profile/[userId]/_components/ProfileContents.tsx
  src/app/(auth)/profile/[userId]/_components/ProfileEdit.tsx
  src/app/(auth)/profile/[userId]/_components/ProfileInfo.tsx
  src/app/(auth)/profile/[userId]/_components/ProfilePage.tsx
  src/app/(auth)/profile/[userId]/_components/Timeline.tsx
  src/app/(auth)/profile/[userId]/_components/UserProfile.tsx
  src/app/(auth)/profile/[userId]/_components/UserProfileStats.tsx
  src/app/(auth)/profile/[userId]/page.tsx
  src/components/atoms/button/OptionButton.stories.tsx
  src/components/atoms/button/OptionButton.tsx
  src/components/atoms/button/Tab.stories.tsx
  src/components/atoms/button/Tab.tsx
  src/components/atoms/cardHoverMsg/CardHoverMsg.stories.tsx
  src/components/atoms/cardHoverMsg/CardHoverMsg.tsx
  src/components/atoms/cardHoverMsg/index.ts
  src/components/atoms/userTimeline/UserTimeline.stories.tsx
  src/components/atoms/userTimeline/UserTimeline.tsx
  src/components/atoms/userTimeline/index.ts
  src/components/molecules/myFeedCard/MyFeedCard.stories.tsx
  src/components/molecules/myFeedCard/MyFeedCard.tsx
  src/components/molecules/myFeedCard/index.ts
  src/components/organisms/header/Header.tsx
  src/components/svg/EditSVG.tsx
  src/hooks/useTabController.ts
  src/types/props.ts
Labels: ✨ Feat

#41 Feat/signup
  src/app/(auth)/_hooks/useAuth.ts
  src/app/(auth)/_hooks/useEmailConfirm.ts
  src/app/(auth)/_hooks/useFormData.ts
  src/app/(auth)/login/_components/SocialLoginBtn.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/types/authType.ts
  src/utils/zodSchema.ts
Labels: ✨ Feat
