Repository All-eatery/EatsFinder-FE, pull requests merged in 2024-06, with the labels that each got.

#4 Feat/button
  package-lock.json
  package.json
  src/app/globals.css
  src/components/atoms/button/Button.tsx
  src/components/atoms/button/MoreButton.tsx
  src/components/atoms/button/index.ts
  src/components/atoms/index.ts
  tailwind.config.ts
Labels: ✨ Feat

#5 Feat/input
  public/icon/close_login.svg
  src/app/_componets/Text.tsx
  src/app/page.tsx
  src/components/atoms/Textfield.tsx
  src/components/svg/AddSVG.tsx
  src/components/svg/AlarmlightSVG.tsx
  src/components/svg/CheckBoxSVG.tsx
  src/components/svg/CheckSVG.tsx
  src/components/svg/CloseSVG.tsx
  src/components/svg/Close_loginSVG.tsx
  src/components/svg/DefaultIconSVG.tsx
  src/components/svg/DeleteSVG.tsx
  src/components/svg/DownSVG.tsx
  src/components/svg/DropdownSVG.tsx
  src/components/svg/DropupSVG.tsx
  src/components/svg/EditSVG.tsx
  src/components/svg/ErrorSVG.tsx
  src/components/svg/FavSVG.tsx
  src/components/svg/FilterSVG.tsx
  src/components/svg/HashtagSVG.tsx
  src/components/svg/InvisigilitySVG.tsx
  src/components/svg/LocationSVG.tsx
  src/components/svg/LockSVG.tsx
  src/components/svg/MarklocationSVG.tsx
  src/components/svg/MeatballSVG.tsx
  src/components/svg/MenuSVG.tsx
  src/components/svg/MoreSVG.tsx
  src/components/svg/MyLocationSVG.tsx
  src/components/svg/NotiSVG.tsx
  src/components/svg/OfficialLogoSVG.tsx
  src/components/svg/RatingstarSVG.tsx
  src/components/svg/RightSVG.tsx
  src/components/svg/SearchSVG.tsx
  src/components/svg/ShareSVG.tsx
  src/components/svg/SocialSVG.tsx
  src/components/svg/VisibilitySVG.tsx
Labels: ✨ Feat, 🍱 Add

#10 Feat/textfield btn
  src/app/_componets/Test.tsx
  src/app/_componets/Text.tsx
  src/app/layout.tsx
  src/components/atoms/Textfield.tsx
  src/components/molecules/TexTFieldWithBtn.tsx
Labels: ✨ Feat

#12 Feat/button
  src/components/atoms/button/Button.tsx
  src/utils/customTwMerge.ts
Labels: ✨ Feat, 🐛 Fix

#14 Feat/storybook
  .eslintrc.json
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/components/atoms/button/Button.stories.tsx
  src/components/atoms/button/MoreButton.stories.tsx
  src/components/atoms/button/MoreButton.tsx
Labels: ✨ Feat, 📁 Chore

#16 Fix/workflows
  .github/workflows/chromatic.yml
Labels: 🐛 Fix

#18 Feat/card
  src/components/atoms/checkbox/Checkbox.stories.tsx
  src/components/atoms/checkbox/Checkbox.tsx
  src/components/atoms/checkbox/index.ts
  src/components/atoms/index.ts
  src/components/molecules/card/Card.stories.tsx
  src/components/molecules/card/Card.tsx
  src/components/molecules/card/index.ts
  src/components/molecules/index.ts
  src/components/svg/BookmarkSVG.tsx
  src/components/svg/CheckBoxSVG.tsx
  tailwind.config.ts
Labels: ✨ Feat

#19 Feat/font
  .storybook/main.ts
  .storybook/preview.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/fonts/index.ts
  tailwind.config.ts
Labels: ✨ Feat

#21 Feat/login page
  package-lock.json
  package.json
  public/icon/close_login.svg
  src/app/(auth)/_components/AuthHeader.tsx
  src/app/(auth)/_hooks/useFormData.ts
  src/app/(auth)/_hooks/useSaveLoginState.ts
  src/app/(auth)/find-account/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/login/_components/LoginPage.tsx
  src/app/(auth)/login/_components/RecentLoginMsg.tsx
  src/app/(auth)/login/_components/SaveLoginState.tsx
  src/app/(auth)/login/_components/SocialLoginBtn.tsx
  src/app/(auth)/login/_components/VisibilityButtonIcon.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_componets/Test.tsx
  src/app/hooks/useToggleHandler.ts
  src/app/page.tsx
  src/app/types/authType.ts
  src/components/atoms/TextField.tsx
  src/components/atoms/spacer/Spacer.tsx
  src/components/atoms/spacer/index.ts
  src/components/atoms/textField/TextField.stories.tsx
  src/components/atoms/textField/TextField.tsx
  src/components/atoms/textField/index.ts
  src/components/molecules/texTFieldWithBtn/TexTFieldWithBtn.stories.tsx
  src/components/molecules/texTFieldWithBtn/TexTFieldWithBtn.tsx
  src/components/molecules/texTFieldWithBtn/index.ts
  src/components/svg/CurrentLoginMsgSVG.tsx
  src/components/svg/DefaultIconSVG.tsx
  src/components/svg/FavSVG.tsx
  src/components/svg/InvisibilitySVG.tsx
  src/components/svg/LogoSVG.tsx
  src/components/svg/RatingstarSVG.tsx
  src/components/svg/SocialSVG.tsx
Labels: ✨ Feat, 📁 Chore
