Repository All-eatery/EatsFinder-FE, pull requests merged in 2024-09, with the labels that each got.

#52 Feat/new post
  src/api/post.ts
  src/app/post/new/_components/NewPostPage.tsx
  src/app/post/new/_components/postForm/PostForm.tsx
  src/app/post/new/_components/postForm/PostFormLeftSection.tsx
  src/app/post/new/_components/postForm/PostFormRightSection.tsx
  src/app/post/new/_components/postForm/index.ts
  src/app/post/new/_components/postForm/postFormElement/index.ts
  src/app/post/new/_components/postForm/postFormElement/postFormLabel/PostFormLabel.tsx
  src/app/post/new/_components/postForm/postFormElement/postFormLabel/index.ts
  src/app/post/new/_components/postForm/postFormElement/postImageField/PostImageField.tsx
  src/app/post/new/_components/postForm/postFormElement/postImageField/PostPreview.tsx
  src/app/post/new/_components/postForm/postFormElement/postImageField/index.ts
  src/app/post/new/_components/postForm/postFormElement/postKeywordField/PostKeywordField.tsx
  src/app/post/new/_components/postForm/postFormElement/postKeywordField/index.ts
  src/app/post/new/_components/postForm/postFormElement/postMenuField/MenuTag.tsx
  src/app/post/new/_components/postForm/postFormElement/postMenuField/PostMenuField.tsx
  src/app/post/new/_components/postForm/postFormElement/postMenuField/index.ts
  src/app/post/new/_components/postForm/postFormElement/postPlaceField/Place.tsx
  src/app/post/new/_components/postForm/postFormElement/postPlaceField/PostPlaceField.tsx
  src/app/post/new/_components/postForm/postFormElement/postPlaceField/PostPlaceSearch.tsx
  src/app/post/new/_components/postForm/postFormElement/postPlaceField/index.ts
  src/app/post/new/_hooks/usePostForm.ts
  src/app/post/new/_hooks/usePostFormContext.ts
  src/app/post/new/page.tsx
  src/app/posts/[postId]/_components/postContent/KeywordChips.tsx
  src/app/posts/[postId]/_components/postContent/Keywords.tsx
  src/app/posts/[postId]/_components/postContent/PostContent.tsx
  src/app/posts/[postId]/_components/postContent/StoreMap.tsx
  src/app/posts/[postId]/page.tsx
  src/components/atoms/chip/Chip.tsx
  src/components/atoms/textField/TextField.tsx
  src/components/molecules/imageInput/ImageInput.stories.tsx
  src/components/molecules/imageInput/ImageInput.tsx
  src/components/molecules/imageInput/index.ts
  src/components/molecules/index.ts
  src/components/molecules/rating/Rating.stories.tsx
  src/components/molecules/rating/Rating.tsx
  src/components/molecules/rating/index.ts
  src/components/molecules/search/Search.tsx
  src/components/molecules/texTFieldWithBtn/TexTFieldWithBtn.tsx
  src/components/svg/CloseSVG.tsx
  src/constants/keywords.ts
  src/hooks/useDebounce.ts
  src/types/postType.ts
  src/utils/hangul.ts
  src/utils/parseKeywords.ts
  src/utils/zodSchema.ts
  tailwind.config.ts
Labels: ✒️ Rename, ✨ Feat, 🐛 Fix

#54 🐛 Fix/build
  src/components/organisms/header/Header.tsx
Labels: 🐛 Fix

#55 🧪 Test: fork 최신화 테스트
  .github/workflows/deploy.yml
  build.sh
  src/components/organisms/header/Header.tsx
Labels: 🧪 Test

#56 🧪 Test: target-branch 수정
  .github/workflows/deploy.yml
Labels: 🧪 Test

#58 🐛 Fix: 로그인 405 에러 수정(#57)
  src/app/api/auth/login/route.ts
  src/app/api/auth/route.ts
Labels: ♻️ Refactor

#60 Feat/delete account page
  src/app/(auth)/_hooks/useAuth.ts
  src/app/(auth)/_hooks/useDeleteReason.ts
  src/app/(auth)/_hooks/useEmailConfirm.ts
  src/app/(auth)/_hooks/useFormData.ts
  src/app/(auth)/_hooks/useSaveLoginState.ts
  src/app/(auth)/delete-account/_components/DeleteAccountForm.tsx
  src/app/(auth)/delete-account/_components/DeleteAccountPage.tsx
  src/app/(auth)/myaccount/[userId]/_components/MyAccountPage.tsx
  src/app/(auth)/profile/[userId]/_components/ProfileEdit.tsx
  src/app/(auth)/signup/_components/ConfirmEmail.tsx
  src/components/atoms/checkbox/Checkbox.tsx
  src/components/atoms/iconWithText/IconWithText.stories.tsx
  src/components/atoms/iconWithText/IconWithText.tsx
  src/components/atoms/iconWithText/index.ts
  src/components/molecules/userDropdownMenu/UserDropdownMenu.tsx
  src/components/organisms/header/Header.tsx
  src/components/svg/CheckBoxSVG.tsx
  src/hooks/useDropdownHandler.ts
  src/middleware.ts
  src/types/authType.ts
  src/utils/zodSchema.ts
Labels: ✨ Feat

#62 Feat/new post
  src/api/post.ts
  src/app/post/new/_components/postForm/postFormElement/postMenuField/PostMenuField.tsx
  src/app/post/new/_hooks/usePostFormContext.ts
  src/types/responseType.ts
Labels: ✨ Feat, 🐛 Fix
